[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

[pyprland.variables]
term_classed = "kitty --class"
ferdium_classed = "ferdium --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.ferdium-chat]
animation = "fromTop"
command = "[ferdium_classed] --class main-ferdium"
class = "main-ferdium"
size = "75% 75%"
max_size = "1920px 100%"
